name = "FreeBird"
uuid = "b4936512-85e8-430f-a91d-7f510ed448a2"
authors = ["Ray Yang <mingrui.yang@outlook.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
